include: package:very_good_analysis/analysis_options.yaml

analyzer:
  errors:
    missing_code_block_language_in_doc_comment: ignore
    lines_longer_than_80_chars: ignore
    public_member_api_docs: ignore
    document_ignores: ignore
    no_default_cases: true
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  plugins:
    - custom_lint
linter:
  rules:
    prefer_relative_imports: false
    always_put_control_body_on_new_line: false
    sort_pub_dependencies: false
    avoid_classes_with_only_static_members: false
    use_setters_to_change_properties: false
    avoid_print: false
    one_member_abstracts: false
    flutter_style_todos: false
    unawaited_futures: true
    cancel_subscriptions: true
    eol_at_end_of_file: true
    prefer_const_constructors: true
    use_build_context_synchronously: true
    always_put_required_named_parameters_first: true
    prefer_asserts_with_message: true
    avoid_equals_and_hash_code_on_mutable_classes: true
    use_if_null_to_convert_nulls_to_bools: true
    missing_whitespace_between_adjacent_strings: true
    avoid_escaping_inner_quotes: true
    leading_newlines_in_multiline_strings: true
    unnecessary_raw_strings: true
    use_raw_strings: true
    prefer_if_elements_to_conditional_expressions: true
