name: flutter_profile_web_33
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  # Network
  url_launcher: ^6.3.1
  http: ^1.3.0

  # UI
  shimmer_animation: ^2.2.2
  supercharged: ^2.1.1
  sidebarx:
  font_awesome_flutter: ^10.8.0

  # State Management
  flutter_hooks: ^0.20.5
  flutter_riverpod: ^2.6.1
  hooks_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  go_router: ^14.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  # Generator
  build_runner: ^2.4.15
  json_serializable: ^6.9.4
  riverpod_generator: ^2.6.4
  go_router_builder: ^2.8.2
  flutter_gen_runner: ^5.10.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/app/
    - assets/utils/
    - assets/projects/
    - assets/architecture/
